# Generated by Django 3.0.2 on 2020-05-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_article_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_stock', models.IntegerField(default=0)),
                ('max_usd', models.IntegerField(default=0)),
                ('gains', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creterion_sell', models.IntegerField(default=0, verbose_name='売る基準')),
                ('creterion_buy', models.IntegerField(default=0, verbose_name='買う基準')),
                ('interval', models.IntegerField(default=0, verbose_name='投資間隔')),
                ('volume', models.IntegerField(default=0, verbose_name='一回で買う量')),
            ],
        ),
    ]
